### ISSUE TITLE
Mind releasing 1.0.2? (For minimatch dependency update)

### ISSUE THREAD

**Issue by ralphtheninja** [CodeJockey/node-ninja#13]
Got https://github.com/Level/leveldown/issues/294 reported in leveldown and noticed it was fixed [here](https://github.com/CodeJockey/node-ninja/commit/9212d0fd1efaaf2508d32b064d112c5807497ce9)

**Comment by ralphtheninja** [comment]
ping @hintjens

**Comment by hintjens** [comment]
Sorry for the slow response on this. Have been somewhat occupied. Would you
like to take over the release process for node-ninja? I'm a little unable
to do this over the long term.

On Mon, Jul 18, 2016 at 11:57 AM, Lars-Magnus Skog <notifications@github.com

**Comment by ralphtheninja** [comment]
> Sorry for the slow response on this. Have been somewhat occupied. Would you like to take over the release process for node-ninja? I'm a little unable to do this over the long term.

Np Pieter. I'd be happy to do that. But it would be nice if there were more people than just me.

**Comment by rgbkrk** [comment]
I'm happy to make releases as well. I'm rgbkrk on npmjs.com

**Comment by ralphtheninja** [comment]
@hintjens I'm `ralphtheninja` on npmjs.com. Let me know when you've added me. Cheers!

**Comment by hintjens** [comment]
Hmm. So creating an organization means paying $7/month, which I don't
really want to do. The package is currently published under hintjens/,
which is unsustainable since I'm too sick to promise to be around to keep
this going in the long term.

Any other suggestions? Existing organizations on npmjs that would host this
project? Easy to move in github then, to match.

**Comment by ralphtheninja** [comment]
@hintjens There's no need to create an organization on npm. Currently you are the only maintainer on npm:

```
$ npm owner ls node-ninja   
hintjens <pieterh@gmail.com>
```

To add another user to npm, just do (using my nick as example):

```
$ npm owner add ralphtheninja node-ninja
```

```
$ npm owner --help
npm owner add <user> [<@scope>/]<pkg>
npm owner rm <user> [<@scope>/]<pkg>
npm owner ls [<@scope>/]<pkg>
```

**Comment by hintjens** [comment]
:-) it works!

Thanks for the explanation.

**Comment by ralphtheninja** [comment]
Cool!

```
$ npm owner ls node-ninja                
hintjens <pieterh@gmail.com>
ralphtheninja <ralphtheninja@riseup.net>
rgbkrk <rgbkrk@gmail.com>
```

**Comment by ralphtheninja** [comment]
`1.0.2` published. Closing.
