### ISSUE TITLE
creating new releases

### ISSUE THREAD

**Issue by ralphtheninja** [CodeJockey/node-ninja#5]
If I do `npm info node-ninja` it tells me the latest version is `0.4.0` but when I check `package.json` of the project it's `0.3.0` which is somewhat confusing to me.

I propose we use `npm version major|minor|patch` when creating a new release. This command creates a new commit in git, tags it and updates `package.json` and is a common workflow when releasing modules to npm.

**Comment by ralphtheninja** [comment]
On a side note, since `prebuild` uses this as a dependency and use `^0.3.0`, it means `prebuild` will not automatically get new minor or patch releases of `node-ninja`. The `^` works differently when the version number is still below `1`. Just a heads up.

**Comment by hintjens** [comment]
OK, thanks for the info. I still need to get to grips with the versioning workflow. `npm version` looks sound. Let me try this on a 0.5.0 release... ok, nice.

What syntax do we use in prebuild to automatically update node-ninja?

**Comment by ralphtheninja** [comment]
> What syntax do we use in prebuild to automatically update node-ninja?

Using `^` is the way to go here (just like we use for `node-gyp`), the problem is that the `node-ninja` version is below `1`. If we play with the thought that `node-ninja` is on version `1.2.3` and in `prebuild` we use `^1.2.3` then when `node-ninja` releases e.g. `1.3.0` then `prebuild` would get `1.3.0` on next install, since `node-ninja` version is above `1`.

**Comment by ralphtheninja** [comment]
> it means prebuild will not automatically get new minor or patch releases of node-ninja

Correction. New patches would be updated, but not new minors.

**Comment by ralphtheninja** [comment]
More information can be found here https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

Easiest would be to just have `node-ninja` start using major, e.g. release `1.0.0` and take it from there. As long as you don't bump major, then minors and patches would automatically be updated on prebuild.

**Comment by hintjens** [comment]
OK, I've got one or two things to fix and then I'll make a 1.0.0 release.

**Comment by ralphtheninja** [comment]
> OK, I've got one or two things to fix and then I'll make a 1.0.0 release.

Rock n roll. Closing this.

**Comment by rgbkrk** [comment]
Thanks for bringing this up @ralphtheninja.
